FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app
COPY api-gateway/mvnw api-gateway/pom.xml ./
COPY api-gateway/.mvn ./.mvn/
COPY api-gateway/src ./src
RUN chmod +x mvnw && ./mvnw clean package -DskipTests -q

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8084
ENTRYPOINT ["java", "-jar", "app.jar"]
