services:
  ms-ventas:
    build:
      context: .
      dockerfile: Dockerfile.ms-ventas
    image: bootstian/ms-ventas:latest
    ports:
      - "9081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-lucky-cloud-ami42tlw-pooler.c-5.us-east-1.aws.neon.tech/neondb?currentSchema=ventas&sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_RkUIf1wX4uDx
      - SERVER_PORT=8081
    restart: unless-stopped

  ms-datos-org:
    build:
      context: .
      dockerfile: Dockerfile.ms-datos-org
    image: bootstian/ms-datos-org:latest
    ports:
      - "9082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-lucky-cloud-ami42tlw-pooler.c-5.us-east-1.aws.neon.tech/neondb?currentSchema=datos_org&sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_RkUIf1wX4uDx
      - SERVER_PORT=8082
    restart: unless-stopped

  ms-indicadores:
    build:
      context: .
      dockerfile: Dockerfile.ms-indicadores
    image: bootstian/ms-indicadores:latest
    ports:
      - "9083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-lucky-cloud-ami42tlw-pooler.c-5.us-east-1.aws.neon.tech/neondb?currentSchema=indicadores&sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_RkUIf1wX4uDx
      - SERVER_PORT=8083
    restart: unless-stopped

  bff:
    build:
      context: .
      dockerfile: Dockerfile.bff
    image: bootstian/bff:latest
    ports:
      - "9080:8090"
    environment:
      - SERVER_PORT=8090
      - MS_VENTAS_URL=http://ms-ventas:8081
      - MS_DATOS_ORG_URL=http://ms-datos-org:8082
      - MS_INDICADORES_URL=http://ms-indicadores:8083
    depends_on:
      ms-ventas:
        condition: service_started
      ms-datos-org:
        condition: service_started
      ms-indicadores:
        condition: service_started
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.api-gateway
    image: bootstian/api-gateway:latest
    ports:
      - "9084:8084"
    environment:
      - SERVER_PORT=8084
    depends_on:
      ms-ventas:
        condition: service_started
      ms-datos-org:
        condition: service_started
      ms-indicadores:
        condition: service_started
      bff:
        condition: service_started
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: bootstian/frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - api-gateway
    restart: unless-stopped
