FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app
COPY ms-ventas/mvnw ms-ventas/pom.xml ./
COPY ms-ventas/.mvn ./.mvn/
COPY ms-ventas/src ./src
RUN chmod +x mvnw && ./mvnw clean package -DskipTests -q

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
