sonar.projectKey=grupocordillera_ms-ventas
sonar.projectName=Grupo Cordillera - MS Ventas
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.java.binaries=.
sonar.exclusions=**/target/**,**/node_modules/**,**/frontend/**
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.java.coveragePlugin=jacoco
